# Generated by Django 3.1.2 on 2020-10-07 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leveling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='leveled Up Date')),
                ('exp', models.CharField(choices=[('HP', 'Hitpoints'), ('DE', 'Defense'), ('AT', 'Attack')], default='HP', max_length=2)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.character')),
            ],
        ),
    ]
